name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Vite Site
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy
        uses: actions/deploy-pages@v2
