name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [main]  # Trigger on push to the main branch

permissions:
  contents: write  # Allows actions to push to the repository
  pages: write     # Allows actions to deploy to GitHub Pages
  id-token: write  # Required for the deploy-pages action to authenticate

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu VM

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out the repository to the runner

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Defines the Node.js version to use

      - name: Install Dependencies
        run: npm ci  # Installs dependencies using npm

      - name: Build Vite Site
        run: npm run build  # Builds the Vite project

      - name: List Files in Dist
        run: ls -la ./dist  # Debugging: List files to ensure the dist folder is being generated correctly

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # Deploys the build to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Uses the GitHub token for authentication
          publish_dir: ./dist  # Path to the build output directory
