name: Deploy Astro site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Print Node.js version
        run: node -v

      - name: Print npm version
        run: npm -v

      - name: Install dependencies
        run: npm install

      - name: Print installed dependencies
        run: npm list

      - name: Build Astro site
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name 'stevenportas'
          git config --global user.email 'stevenportas@example.com'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
